[tasks.db-setup]
script_runner = "@shell"
script = '''
docker stop rpts
docker rm rpts
docker run -d --name rpts --net=host -e POSTGRES_PASSWORD=rustmola -p 5432:5432 postgres
docker logs -f rpts
'''

[tasks.db-migrate]
script_runner = "@shell"
script = '''
docker run --name rpts -e POSTGRES_PASSWORD=password -p 5432:5432 -d postgres:latest
sqlx database create
sqlx migrate run
'''

[tasks.echo]
command = "echo"
args = ["hola"]